### ISSUE TITLE
Solicitud borrar perfil de Liliana Villanueva departamento de quimica en notaso 

### ISSUE THREAD

**Issue by Lilianavill** [jpadilla/notaso#115]
Saludos

Me comunico para solicitar por favor eliminen el perfil que crearon en mi nombre como docente en el departamento de química ya que  esta atentando contra mi integridad profesional, porque la evaluación dada es completamente no veraz ya que no va acorde con mi perfil profesional. 

Agradezco no acepten crear un perfil en mi nombre porque no estoy de acuerdo con los comentarios que suministran aquí.

Espero pronta respuesta a mi solicitud
Gracias

**Comment by jpadilla** [comment]
resuelto.
