### ISSUE TITLE
Rest API Update - Buscar profe por University > Departments > Profesors > Profesor

### ISSUE THREAD

**Issue by jorgeluis11** [jpadilla/notaso#87]
Estaba usando el Rest API y andaba creando una sección para buscar profesores pero por universidad>departamento>lista de profesores de ese departamento.  Ya que es algo que algunos usuarios me han escrito por feedback o por alguna red social.  

Aquí una foto de como se ve la sección de las universidades por ahora.

![10985480_798791316883147_6537120524799720396_n 1](https://cloud.githubusercontent.com/assets/2798483/7506823/6864ec42-f433-11e4-8b61-77ff0229769f.jpg)

Cualquier cosa que necesiten ayuda en algo estoy dispuesto a ayudar y dispuesto a meterle a ember para la nueva version.

**Comment by kekivelez** [comment]
Seria util que agreges un milestone a github indicando en que especifico se esta trabajando de este feature. Por ejemplo iba a reportar que cuando hace busqueda por universidades (en esa pagina) el menu contextual (las tres rayas) dejan de funcionar y tampoco puedes undir en las universidades para abrir la pagina de la universidad, al menos en android que fue donde lo estaba probando. Puede ser que esto este en proceso pero mirando el github no lo se.

**Comment by luisjorge129** [comment]
Solucionado con la versión 2 del api, ejemplo de una busqueda de profesores que este en el departamento de Ciencias de Computadora en la UPR de Bayamón: [https://notaso.com/api/v2/universities/uprb/?department=ciencias-de-computadora](https://notaso.com/api/v2/universities/uprb/?department=ciencias-de-computadora)

@Jpadilla1
